ajustes nec

diff --git a/.github/workflows/build-and-tests.yml b/.github/workflows/build-and-tests.yml
--- a/.github/workflows/build-and-tests.yml
+++ b/.github/workflows/build-and-tests.yml
@@ -6,6 +6,10 @@ on:
   push:
     branches: [main]
 
+permissions:
+  checks: write
+  contents: read
+
 jobs:
   build-and-test:
     runs-on: ubuntu-latest
@@ -13,7 +17,7 @@ jobs:
       - name: Checkout source code
         uses: actions/checkout@v4
 
-      - name: Setup .NET 9 
+      - name: Setup .NET 9 (Preview)
         uses: actions/setup-dotnet@v4
         with:
           dotnet-version: '9.0.x'
@@ -24,8 +28,10 @@ jobs:
       - name: Build solution
         run: dotnet build --configuration Release --no-restore
 
-      - name: Run unit tests (continue on failure)
-        run: dotnet test --configuration Release --no-build --logger "trx;LogFileName=results.trx" --results-directory TestResults
+      - name: Run unit tests and store result
+        id: test
+        run: |
+          dotnet test --configuration Release --no-build --logger "trx;LogFileName=results.trx" --results-directory TestResults || echo "TEST_FAILED=true" >> $GITHUB_ENV
         continue-on-error: true
 
       - name: Publish test report
@@ -35,3 +41,7 @@ jobs:
           results-directory: TestResults
           report-name: Test Results
           report-title: Detailed Test Results
+
+      - name: Fail workflow if tests failed
+        if: env.TEST_FAILED == 'true'
+        run: exit 1
