ajustes

diff --git a/.github/workflows/build-and-tests.yml b/.github/workflows/build-and-tests.yml
--- a/.github/workflows/build-and-tests.yml
+++ b/.github/workflows/build-and-tests.yml
@@ -33,6 +33,15 @@ jobs:
         uses: zyborg/dotnet-tests-report@v1
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
-          project_path: Test                  
+          project_path: Test
           report_name: domnum_tests
           report_title: Domnum - Test Results
+
+      - name: Fail workflow if any test failed
+        run: |
+          if grep -q "<Outcome>Failed</Outcome>" Test/TestResults/test-results.trx; then
+            echo "❌ Some tests failed. Failing the job to block merge.";
+            exit 1
+          else
+            echo "✅ All tests passed.";
+          fi
